package ArithApp.basicserverPackage;


/**
* ArithApp/basicserverPackage/arrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Monday, June 20, 2005 11:55:04 AM PDT
*/

public final class arrayHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public arrayHolder ()
  {
  }

  public arrayHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ArithApp.basicserverPackage.arrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ArithApp.basicserverPackage.arrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ArithApp.basicserverPackage.arrayHelper.type ();
  }

}
