package ArithApp;


/**
* ArithApp/_basicserverStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Monday, June 20, 2005 11:55:03 AM PDT
*/

public class _basicserverStub extends org.omg.CORBA.portable.ObjectImpl implements ArithApp.basicserver
{

  public void addArrays (int[] aa, int[] bb, ArithApp.basicserverPackage.arrayHolder result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addArrays", true);
                ArithApp.basicserverPackage.arrayHelper.write ($out, aa);
                ArithApp.basicserverPackage.arrayHelper.write ($out, bb);
                $in = _invoke ($out);
                result.value = ArithApp.basicserverPackage.arrayHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addArrays (aa, bb, result        );
            } finally {
                _releaseReply ($in);
            }
  } // addArrays

  public void upper2lower (double xx, double yy, org.omg.CORBA.DoubleHolder result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("upper2lower", true);
                $out.write_double (xx);
                $out.write_double (yy);
                $in = _invoke ($out);
                result.value = $in.read_double ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                upper2lower (xx, yy, result        );
            } finally {
                _releaseReply ($in);
            }
  } // upper2lower

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ArithApp/basicserver:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _basicserverStub
