package ArithApp;


/**
* ArithApp/basicserverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Monday, June 20, 2005 11:55:04 AM PDT
*/

public interface basicserverOperations 
{
  void addArrays (int[] aa, int[] bb, ArithApp.basicserverPackage.arrayHolder result);
  void upper2lower (double xx, double yy, org.omg.CORBA.DoubleHolder result);
} // interface basicserverOperations
