package ArithApp;


/**
* ArithApp/basicserver.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from test.idl
* Monday, June 20, 2005 11:55:04 AM PDT
*/

public interface basicserver extends basicserverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
  public static final short SIZE = (short)(10);
} // interface basicserver
